[package]
name = "natas_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["cookies"] }
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread", "net"] }
